#+TITLE: Outreach Portal
#+AUTHOR: VLEAD
#+DATE: [2016-02-05 Fri]
#+PROPERTY: results output
#+PROPERTY: exports code
#+SETUPFILE: ./org-templates/level-0.org
#+options: ^:nil


* Introduction
  [[www.vlabs.ac.in][Virtual Labs]] is an initiative of Ministry of Human Resources, India.  Virtual
  Labs is intended to augment the learning of engineering subjects through
  performing experiments.  The experiments are designed either as simulations
  or as remote triggered.  A remote triggered lab allows a user to connect to
  real equipment using a web browser.  There are around 150 and labs and 1500
  experiments.

  The evolution of virtual labs is a function of realization of the ideas
  listed here.  Some of them are work in progress and others are yet to make a
  takeoff.

* Presence
** IRC Channels
   1. #vlead :: used by the community developing the infrastructure for Virtual
                Labs.
   2. #vlabs-integrators :: used by lab developers and integrators.

   Both the channels are on freenode network. 

** Sources
   1. www.github.com/vlead :: sources of projects related to infrastructure of
        Virtual Labs
   2. www.github.com/Virtual-Labs :: sources of different labs that make up
        Virtual Labs

** Documentation
** Mailing List

* Ideas
** Experiment as a Service
   Experiment as a Service is a runtime environment that is a congealment
   of various javascript objects to provide a mechanism to log the entire event
   space of interaction, viz. listening to an audio clip, running a simulation
   etc,.  This event log is provided as a service via REST API for the
   encompassing application to provide persistence, analytics, quizzes
   etc. based on the user's progress. 

   For more information refer to the [[https://github.com/vlead/virtual-labs-as-a-service/blob/master/src/index.org][architecture]].


** Authentication between different software services at VLEAD
   Virtual Labs is supported by a slew of micro services. [[https://github.com/vlead/ovpl][ADS]] - Auto Deployment
   Service is used to deploy a virtual lab.  This service transforms a src url
   on github to a hosted url with a domain name.  [[https://github.com/vlead/dataservice][dataservice]] is another
   service which acts as a central repository of information about virtual
   labs.  [[https://github.com/vlead/outreach-portal.git][Outreach Portal]] feeds from another service specifically built for the
   portal.  These services could potentially be used by either other services
   are other portals.  A mechanism needs to be built to ensure only authorized
   users/services have access to the data and provide a way to authenticate
   these authorized users/services.


** Developing different portals
   Portals that consume data from the services and provide an interface to the
   users are an important ingredient of Virtual Labs.  
   
   One such portal is [[http://outreach.vlabs.ac.in/][outreach portal]] that is in production.  The sources are
   at http://github.com/vlead/outreach-portal.git 

   A [[https://github.com/vlead/vlabs-dashboard][virtual labs dashboard]] that provides information about all the virtual
   labs - what are the technologies used by the lab, what is the source
   repository of a lab, etc., - is in pipeline.

   A portal that supports lab development and continuous integration needs to
   be built.  This portal helps a lab developer to host a lab in a test
   environment and allow a developer to post a request to host it in
   production.  This portal can also provide run time health and statics of any
   lab that running in a VM.


** Automation of Test Cases
   Each virtual lab is a web application.  Testing of the web application by
   running through the user scenarios is manual right now.  These integrated
   test cases have to automated.  This will greatly help the cause of
   continuous integration where these integrated test cases could be run after
   the web application is deployed. 


** Continuous Integration
   A lab is currently defined as a set of related experiments and is a web
   application.  Each lab is a repository on github.  To ensure evolution of
   software and solicit contribution from folks across the world, continuous
   integration is to be built around each lab.  A cycle for integration will
   involve building the code, running the unit test cases, hosting the
   application and running the integration tests. 


** AWS Lambda
   Currently each virtual lab runs from an individual Amazon Webservices(AWS)
   VM.  Virtual Labs would like to explore AWS Lambda that allows execution of
   requested code.  Virtual Labs are a collection of simulations and each
   simulation is associated with code, running a simulation is equivalent to
   running the code on demand.  Harnessing AWS Lambda could significantly
   reduce the costs of hosting Virtual Labs.


** Renarration

** Experiment Implementation from a paper prototype
